# python of course and we don't need access to sudo atm
language: python
sudo: true

# emails are annoying
notifications:
    email: false

# build on Ubuntu 14.04 because the default is
# really old
os: linux
dist: trusty

# test on the latest version of python
python:
    - "3.6"

# only run travis on the master branch
branches:
    only:
        - master

# install dependencies listed in requirements
install: 
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    - conda env create
    - source activate sortingAlgorithms

# run tests
script:
    "python -m pytest -v test/*"
